### ISSUE TITLE
Recreation of images has changed with the latest commit, plus more noise.

### ISSUE THREAD

**Issue by rundiffusion** [SeargeDP/SeargeSDXL#13]
This image was created with commit 5e18a21aa6ac80d3eb1fcc28b19cf34273ed71dd from Jul 28, 2023
https://storage.googleapis.com/comfy-images/iron-man-lava-suit-5e18a21aa6ac80d3eb1fcc28b19cf34273ed71dd.png

This image was created from commit 5a61f08e464c54aead5bf920dc4b6d96af25b1c4
https://storage.googleapis.com/comfy-images/Iron-man-lava-suit-5a61f08e464c54aead5bf920dc4b6d96af25b1c4.png

These images should have the metadata attached.

Something has changed. I wanted you to be aware of the issue as I have to stay on commit 5e18a21aa6ac80d3eb1fcc28b19cf34273ed71dd until this is fixed because I've created a whole bunch of tutorials that need the images to recreate.

**Comment by SeargeDP** [comment]
That is a known side effect from a recent bug fix.

But I will consider the option to make this fix optional in the next update, potentially as a "style switch". In that case you'd just have to mention that option in the tutorials instead of re-creating all your images.

And thanks for the feedback, in the future I'll add an option to switch it on or off if I ever have to make a change that changes the output images. Hopefully this was the last and only case where that happened.

**Comment by SeargeDP** [comment]
And for now, I recommend sticking to the older version of the workflows and extension if you make more example images until the fix is implemented. Images from v2.1, when dropped in the next update, will not generate the same images from the metadata. The migration path of loading a v2.0 image in v2.2 should work.

**Comment by SeargeDP** [comment]
Ok, one more. I've looked into the images you linked and the commits you mentioned. You are using an extremely old version of the workflow and extension, even before v2.0 was released.

It might be annoying, but I really recommend creating new example images with the latest release v2.1 - going forward I can only maintain compatibility between older and newer versions of the workflows and extensions if you do that.

Alternatively, if you don't want to update the images and tutorials, I recommend forking the repository and using that version. But in that case you won't be able to benefit from future updates to this project anymore. For example when I add controlnet in the future (when that becomes available), or other improvements.

In v2.x the whole graph layout and user interface has been overhauled and re-created from scratch to provide a good user experience with these workflows. Look at the screenshots on my CivitAI page to see what I'm referring to: https://civitai.com/images/1815870?modelVersionId=130616

**Comment by SeargeDP** [comment]
I've joined the Discord. Definitely a good idea to have a chat soon, so I can explain the motivation and goals of this project. I highly recommend to have that chat first before you start re-generating images with the new workflow :)

**Comment by SeargeDP** [comment]
Coming back to this topic, could you please test commit `ccdc3293b71048e62614e928908bfbbdd64ec2eb` with your originally created image and tell me if you can generate the image that you originally made for your tutorials?

Also, if you are still planning to update to newer versions of the workflow and generating new images, I **really** recommend that we have a short chat before you do so. There is one more change coming up very soon that may affect backwards compatibility, but the purpose of that change is to make future updates always backwards compatible with older versions of workflows.

**Comment by SeargeDP** [comment]
Version 3.4 was released 2 days ago and it has improved compatibility with the example images on your website. I tried some of them and they were generating the same images that you have on the site. So you may want to consider updating to the latest version, instead of sticking to the old version of my extension. That would also make it easier for your users to run newer versions of my workflow on your service.

If you want examples for creating similar images as the ones you have on the site, reach out to me and I can send you some examples made with the latest version of my Comfy workflow. I've joined your Discord server some time ago, so that's where you can find me.

![image](https://github.com/SeargeDP/SeargeSDXL/assets/3330978/4b23ff47-dd57-4ca4-82d7-4af31f4311c9)

**Comment by SeargeDP** [comment]
I will close this issue, v3.4 is compatible with your example images
