### ISSUE TITLE
Is it possible to make a more detailed guidance document？

### ISSUE THREAD

**Issue by BoosterCore** [SeargeDP/SeargeSDXL#5]
Would you please explain, what is "prompt G" and  "prompt L" and “prompt R”?

**Comment by SeargeDP** [comment]
Until SDXL 1.0 is released it's still a bit unclear how it will work in the end.

For SDXL Beta 0.9 the base model uses 2 CLIP models and the general idea seems to be that the CLIP G prompt encoder is best used for the image subject and CLIP L seems to be more of a supporting prompt to define the style of the image.

Prompt R is just the prompt that the refiner uses, it has little impact on the final image unless you use a very low base ratio (less than 0.5) and for now I suggest to just use the same as prompt G because the refiner also uses a CLIP G model internally.

It also seems, from my experiments so far, that CLIP G is better at understanding full sentences and CLIP L better understands lists of tags, similar to how SD 1.5 is prompted.

**Comment by BoosterCore** [comment]
Thank U very much！！！！

**Comment by SeargeDP** [comment]
A prompting guide is included on the latest release of the workflows. I'll close this ticket.
