### ISSUE TITLE
Selecting another detail_preprocess in the Searge-SDXL-Reborn-v4_1workflow?

### ISSUE THREAD

**Issue by wes-kay** [SeargeDP/SeargeSDXL#77]
I'm trying to set the preprocess refiner in `Searge-SDXL-Reborn-v4_1.json` but I'm not able to, as it's not showing up in the selector, the only way I'm adding my own preprocessor is by modifying the .json directly from the `1x-ITF-SkinDiffDetail-Lite-v1.pth` to my updated preprocessor: 

```
     "title": "Upscale Models Selector",
      "properties": {
        "Node name for S&R": "SeargeUpscaleModels"
      },
      "widgets_values": [
        "001_classicalSR_DIV2K_s48w8_SwinIR-M_x4.pth",
        "4x_Nickelback_70000G.pth",
        "4x-UltraSharp.pth",
        "4x_NMKD-Siax_200k.pth"
      ],

```

My solution works, but it's a pain when I want to drag in new images for their workflows as it resets everything. 
Is this a bug, or is it done on purpose?

![image](https://github.com/SeargeDP/SeargeSDXL/assets/40011470/3ac1aaa7-38ea-43f9-83ce-085a7e69dac3)

**Comment by SeargeDP** [comment]
Right now the model selectors filter by file name, so if you rename your filter to start with `1x` it should show up. It also looks like you are trying to use a `4x` upscale model as detail processor, but the way it works right now it should be a `1x` model that doesn't change the image resolution.
To use the `4x` model in the process, select it as "high_res_upscaler" instead of "detail_processor"
